### ISSUE TITLE
Beam waist calculation for hg and ig beams

### ISSUE THREAD

**Issue by ilent2** [ilent2/ott#12]
What are the appropriate parameters for w0 for lg and hg beams?  Is there a function to calculate this?

**Comment by AStilg** [comment]
lg_mode_w0 (in my fork, now) will do it for LG modes. For each degree of paraxial modes the beam waist is the same. The parameter input into that file would be: m+n=2p+abs(l)=\lambda etc.

**Comment by AStilg** [comment]
and... it's gone
