### ISSUE TITLE
1.3.1 versus 1.4

### ISSUE THREAD

**Issue by AStilg** [ilent2/ott#18]
I'm thinking that 1.3.1 shouldn't have the GUI as it appears to be a big deal. Suggest putting it in 1.4.

**Comment by ilent2** [comment]
I agree, I'm just looking at Anatolii's code now and I think it would be better to add it to either 1.4 or 1.5.

**Comment by AStilg** [comment]
The matlab gui system uses callbacks in the windows api... have no idea how mathworks do it on linux. It won't be octave compatible.

**Comment by ilent2** [comment]
For faster communication I've setup a slack channel.  Might be a bit easier than opening issues for discussion and a bit faster than email.
