### ISSUE TITLE
Octave and warnings

### ISSUE THREAD

**Issue by AStilg** [ilent2/ott#23]
Octave is not happy about the ott_warning.m function:

error: invalid assignment to cs-list outside multiple assignment

error: invalid empty index list

error: invalid dimension inquiry of a non-existent value

A few options there of what to do, but I'll leave it to you to decide. One way is to make it detect matlab, another way is to leave it out for now? another way is to be very strict with lists and parameters so that it doesn't output "this is not defined" type error.

EDIT: Another option is to release an octave version without warnings.

**Comment by ilent2** [comment]
Fixed in f90b96a7b6545f4545f7e5d3235273fbeed7c574
