### ISSUE TITLE
bsc_pointmatch_focalplane: Unused parameters that should be used

### ISSUE THREAD

**Issue by ilent2** [ilent2/ott#3]
In bsc_pointmatch_focalplane, parameters(1), parameters(2) and parameters(4) are not used.  These should be used or documented as depreciated.

beam_type is not used, however the documentation says it should choose the beam type LG/HG.

**Comment by AStilg** [comment]
Remove the claim that it works for HG beams.
Add a warning that users should use bsc_pointmatch_farfield instead.

**Comment by ilent2** [comment]
Fixed in https://github.com/ilent2/ott/commit/6bcac3d31b6e8764aab559fdc71ddf313e455bbe
