### ISSUE TITLE
Optimisations for beam.translate

### ISSUE THREAD

**Issue by ilent2** [ilent2/ott#30]
- [x] Add A,B matrices as output to all translate functions
- [x] Add option for output Nmax
- [x] Modify `translate_z` to output non-square matrices
- [x] Updates examples and maybe forcetorque to use optimisation

**Comment by ilent2** [comment]
edbbac6

**Comment by ilent2** [comment]
6f6528d -- translate_z now runs much faster, also produces non-square matrices.

**Comment by ilent2** [comment]
We could extend the scatter function to take a position and rotation argument.  This would provide a clean way to hide this optimisation from the user.

**Comment by ilent2** [comment]
d68cef5 -- done.  Still need to optimise examples, they are running really slow.

**Comment by an-kashchuk** [comment]
The default run of beam_visualisation.m has an error.
This command:
slm_beam = beam.translateXyz([5; 0; 0]);
doesn't copy the basis var to slm_beam and it contains 'regular' basis which creates an error in the following farfield calculation.
This will fix it:
slm_beam.basis = 'outgoing';

**Comment by ilent2** [comment]
Good spot.  Thanks, I've fixed it in commit 2cefab9396a8820313ced00f9650c1be392c127e
