### ISSUE TITLE
GUI commands

### ISSUE THREAD

**Issue by an-kashchuk** [ilent2/ott#40]
It would be useful to add (maybe optionally) a printout to the command line of the code used in GUI. E.g. when I press Generate button in any gui window, I want to see which command was executed, so I can use it later in m-files. Also, it might be useful for those trying the toolbox for the first time.

**Comment by ilent2** [comment]
Nice idea.  I've added a menu bar with a Generate Code button to most of the GUIs (its not included in the dynamics GUI yet because I plan to rewrite this for 1.6).

5230b6958534a38d78097c33cc783fe07a1ec63f

**Comment by an-kashchuk** [comment]
Oh, I forgot another issue. Once a gui has been opened, new variables (for Incident beam, Scattered beam) are not picked up. E.g. if both Create and Visualise apps are open and I've created a new var it will not be shown in the drop-list in visualise app.  Could you, please, add an update button or make it automatically.

PS The progress bar is greyed out and it's hard to see the progress.

PSPS The GUI is great. I like it's flexibility!

**Comment by ilent2** [comment]
I've added a button in the menu.  It would be nice to make it automatic, but I'm not sure how to do that without creating a timer to watch for new variables (which I worry could be slow, maybe not too slow though).

I'm not sure about the progress bar.  It should only be grayed out at the start and change to white when the run button is clicked.  I'll take a look into this when I get a chance.  Glad you like the new GUI :)
