### ISSUE TITLE
Setting the T-matrix of particle with other shape in GUI

### ISSUE THREAD

**Issue by STAN-32** [ilent2/ott#45]
Hi Issac, how can I set the T-matrix of particle with cylinder shape in GUI? I set the radius and height with 1e-7 and 3e-6 respectively. But system went worry and told me haven't defined the 'mtimes' function. My MATLAB version is 21b and using toolbox version 1(available in github).

**Comment by wj2392907320** [comment]
Have you solved it now？

**Comment by STAN-32** [comment]
I'm not sure yet, try GUI then select the shape of particle u concerned? make sure the version u use is the newest (gotten in MATLAB instead of github, seems published version in github is not the newest)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月17日(星期天) 晚上10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ilent2/ott] Setting the T-matrix of particle with other shape in GUI (Issue #45)





 
Have you solved it now？

**Comment by ilent2** [comment]
Hi, sorry for my delayed response, I haven't had much time to work on the toolbox lately.  I've just created a new release of the toolbox on github (v1.5.8) that hopefully fixes the problem (it should update on Matworks shortly too).  Please let me know if this doesn't fix the problem or if you encounter any other problems.    Best -- Isaac.
