### ISSUE TITLE
The range of particle sizes to which the program applies

### ISSUE THREAD

**Issue by wj2392907320** [ilent2/ott#47]
Excuse me, this code is applicable to calculate the trapping efficiency of optical tweezers capture how much size range of particles ?

**Comment by ilent2** [comment]
Hi,

the toolbox should be able to calculate scattering of fairly large spherical particles without too much trouble (I'd guess up to about 100 wavelengths should be possible, but would need to check the results carefully).  Other shapes are often less stable, but it really depends on the method you are using to calculate the T-matrix.  For instance, DDA can be used to calculate a T-matrix for a 100 wavelength particle, but on my little home computer I would run out of memory even for a 2 wavelength particle.

Best -- Isaac

**Comment by ilent2** [comment]
I hope that answers your question, or could you expand your question a bit more/provide additional details about what you would like to calculate.

**Comment by wj2392907320** [comment]
> I hope that answers your question, or could you expand your question a bit more/provide additional details about what you would like to calculate.

**Comment by wj2392907320** [comment]
![20220916114228](https://user-images.githubusercontent.com/46819715/190564980-c8b6094f-23c5-4f16-9a17-4023f7fe4662.jpg)
Thank you very much for your detailed reply and I am sorry that it took me so long to think of this problem again. , as shown in the above capture part of the code of this part of the code from the OTT - 1.5.9 / examples/liveScripts/sphere MLX. Excuse me:

1. Is there any size limit to calculate the diameter of microspheres using the T-matrix method?

2. It is written in the literature that T matrix is suitable for the calculation of particles with similar laser wavelength and particle diameter. May I ask whether OTT program package is also suitable for the calculation of particle diameter much larger than the laser wavelength (ray optical model)?

Thanks!

**Comment by ilent2** [comment]
The toolbox should be able to calculate T-matrices for much larger spherical particles.  The maximum value for the slider in the live script was arbitrarily chosen, I think 10*wavelength should work pretty and not take too long, and 100 wavelengths might work but take a little while to calculate.

For larger sizes, it might be good to compare the results to something like geometric optics (you could try using the OTGO package, http://opticaltweezers.org/software/otgo-optical-tweezers-geometrical-optics/).  For large non-spherical particles, OTT doesn't work very well.  If you have another piece of software for calculating the scattering by large non-spherical particles, then you could generate a T-matrix and import it into OTT, but that would be a bit of work.

Best -- Isaac

**Comment by wj2392907320** [comment]
Thank you very much for your detailed reply. Doctor, can the OTT program package you developed calculate the force of hollow vortex optical tweezers? Or any other hollow beam optical tweezers?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ilent2/ott"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 晚上8:53
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ilent2/ott] The range of particle sizes to which the program applies (Issue #47)





 
Closed #47 as completed.

**Comment by ilent2** [comment]
OTT should be able to do this.  This is easiest for Laguerre-Gaussian beams, just set the orbital angular momentum number to some large-ish value (3 or 4 should do).  For other types of beams, you will probably have to do point-matching to calculate the beam shape coefficients for your beam.

If you can describe your beam by a mixture of Laguerre-Gaussian beams, then this might be easier/faster, but depends on what you want to simulate.
